#!/bin/sh
# Generates fontMetricsData.js
PERL="perl"
PYTHON=`python2 --version >/dev/null 2>&1 && echo python2 || echo python`
OUTPUT=../../fontMetricsData.js

cd src/metrics
echo "// This file is GENERATED by buildMetrics.sh. DO NOT MODIFY." >$OUTPUT
$PERL ./mapping.pl | $PYTHON ./extract_tfms.py | $PYTHON ./extract_ttfs.py | $PYTHON ./format_json.py --width >>$OUTPUT
